# Generated by Django 5.2.11 on 2026-02-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='traits',
            field=models.JSONField(default=list),
        ),
    ]
