# Generated by Django 5.2.11 on 2026-02-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_comp_excluded_unit_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='max_trait_counts',
            new_name='excluded_traits',
        ),
    ]
