# Generated by Django 5.2.11 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_rename_max_trait_counts_to_excluded_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_version',
            field=models.CharField(db_index=True, default='16.6 PBE Alpha - No Items THex', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='placement',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='unitusage',
            name='star_level',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['match', 'player'], name='idx_participant_match_player'),
        ),
    ]
