# Generated by Django 5.2.11 on 2026-02-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_performance_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aggregatedunitstat',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live')], db_index=True, default='PBE', max_length=10),
        ),
        migrations.AddField(
            model_name='comp',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live')], db_index=True, default='PBE', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live')], db_index=True, default='PBE', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(db_index=True, default='PBE', max_length=10),
        ),
        migrations.AlterField(
            model_name='aggregatedunitstat',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tracker.unit'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedunitstat',
            unique_together={('unit', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='comp',
            unique_together={('name', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game_name', 'tag_line', 'region')},
        ),
    ]
