# Generated by Django 5.2.11 on 2026-02-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('game_start_time', models.DateTimeField()),
                ('participants', models.JSONField(default=list)),
                ('pro_player_count', models.IntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
