# Generated by Django 5.2.11 on 2026-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_multi_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedunitstat',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live'), ('SCRIMS', 'Scrims')], db_index=True, default='PBE', max_length=10),
        ),
        migrations.AlterField(
            model_name='comp',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live'), ('SCRIMS', 'Scrims')], db_index=True, default='PBE', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='server',
            field=models.CharField(choices=[('PBE', 'PBE'), ('LIVE', 'Live'), ('SCRIMS', 'Scrims')], db_index=True, default='PBE', max_length=10),
        ),
    ]
