# Generated by Django 5.2.11 on 2026-03-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_add_scrims_server_choice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['match', 'placement'], name='idx_part_match_place'),
        ),
        migrations.AddIndex(
            model_name='unitusage',
            index=models.Index(fields=['participant', 'unit'], name='idx_unitusage_participant_unit'),
        ),
    ]
