# Generated by Django 5.2.11 on 2026-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_participant_idx_part_match_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('open', 'Open')], db_index=True, max_length=10, null=True),
        ),
    ]
