# Generated by Django 5.2.11 on 2026-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_player_tier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregatedunitstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aggregatedunitstat',
            name='match_category',
            field=models.CharField(blank=True, choices=[('PROJECT_PBE', 'Project PBE'), ('PRO_RANDOM', 'Pro Random Queue')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedunitstat',
            name='match_tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('open', 'Open')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_category',
            field=models.CharField(blank=True, choices=[('PROJECT_PBE', 'Project PBE'), ('PRO_RANDOM', 'Pro Random Queue')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('open', 'Open')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='counts_for_stats',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedunitstat',
            unique_together={('unit', 'server', 'match_category', 'match_tier')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['server', 'match_category', 'match_tier'], name='idx_match_server_cat_tier'),
        ),
    ]
